use instance variables instead of class variables in salesforce bulk
shubhamgupta731/salesforce_bulk pull request #4
Opened 2017-01-23 09:20 UTC by shubhamgupta731

2017-01-23 09:26 UTC, shivani27 commented
LGTM

2017-01-23 09:28 UTC, shivani27 requested changes

2017-01-23 09:28 UTC, shivani27 commented on lib/salesforce_bulk/job.rb
> +      keys = @records.first.keys
please check here if @records.present?

2017-01-24 05:31 UTC, shubhamgupta731 commented on lib/salesforce_bulk/job.rb
> +      keys = @records.first.keys
as discussed no need to be fixed

2017-01-24 05:46 UTC, shivani27 approved these changes

2017-01-24 07:54 UTC, merged